(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const APP_ORIGIN_SUFFIX = ".googleusercontent.com";
  const state = { reader:null, controls:null, stream:null, track:null, busy:false, lastBarcode:"", lastAt:0, count:0, pending:new Map(), recent:[] };

  function setStatus(text,type=""){ $("cameraStatus").textContent=text; $("cameraStatus").className="status "+type; }
  function beep(ok=true){ try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?930:220;g.gain.value=.06;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(ok?.08:.2));o.onended=()=>c.close()}catch(e){} }
  function send(data){ if(window.opener&&!window.opener.closed) window.opener.postMessage({source:"HOCA_MOBILYA_CAMERA",...data},"*"); }
  function ready(){ send({type:"CAMERA_READY"}); }
  function validAppMessage(event){ const d=event.data||{}; return d.source==="HOCA_MOBILYA_APP"; }
  function renderRecent(){ const el=$("recentList"); if(!state.recent.length){el.innerHTML="<p>Henüz işlem yok.</p>";return;} el.innerHTML="";state.recent.slice(0,20).forEach(x=>{const r=document.createElement("div");r.className="recent-item";r.innerHTML=`<div><strong>${escapeHtml(x.name)}</strong><span>${escapeHtml(x.barcode)} • ${escapeHtml(x.time)}</span></div><b>Stok: ${x.stock}</b>`;el.appendChild(r)}); }
  function escapeHtml(s){return String(s||"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));}
  function submitBarcode(raw){ const barcode=String(raw||"").trim(); if(!barcode||state.busy)return; const now=Date.now(),cool=Number($("cooldownSelect").value||1400); if(barcode===state.lastBarcode&&now-state.lastAt<cool)return; state.lastBarcode=barcode;state.lastAt=now;state.busy=true;$("lastBarcode").textContent=barcode;$("lastResult").textContent="Uygulamaya gönderiliyor...";setStatus("Stok +1 işlemi yapılıyor...");const scanId=Date.now()+"-"+Math.random().toString(36).slice(2);state.pending.set(scanId,barcode);send({type:"BARCODE_SCANNED",barcode,scanId});setTimeout(()=>{if(state.pending.has(scanId)){state.pending.delete(scanId);state.busy=false;$("lastResult").textContent="Uygulamadan cevap alınamadı";setStatus("Apps Script sekmesini açık tutun.","error");beep(false)}},15000); }
  window.addEventListener("message",event=>{if(!validAppMessage(event))return;const d=event.data;if(d.type==="APP_READY"){$("connectionBadge").textContent=(d.personnel||"Uygulama")+" bağlı";$("connectionBadge").className="badge connected";return;}if(d.type==="SESSION_CLOSED"){$("connectionBadge").textContent="Oturum kapandı";$("connectionBadge").className="badge";setStatus("Apps Script oturumu kapatıldı.","error");return;}if(d.type!=="STOCK_RESULT")return;state.pending.delete(String(d.scanId||""));state.busy=false;if(d.success){state.count++;$("successCount").textContent=state.count;$("lastResult").textContent=`${d.productName||"Ürün"} • Yeni stok: ${d.newStock}`;setStatus("Başarılı. Sıradaki barkod bekleniyor...","success");state.recent.unshift({name:d.productName||"Ürün",barcode:d.barcode,stock:d.newStock,time:new Date().toLocaleTimeString("tr-TR")});renderRecent();beep(true);if(navigator.vibrate)navigator.vibrate([60,35,60]);}else{$("lastResult").textContent=d.message||"İşlem başarısız";setStatus((d.message||"İşlem başarısız")+" • Yeni barkod bekleniyor...","error");beep(false);} });
  async function stop(){try{state.controls&&state.controls.stop()}catch(e){}try{state.reader&&state.reader.reset()}catch(e){}if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.controls=null;state.reader=null;state.stream=null;state.track=null;}
  async function loadDevices(){if(!navigator.mediaDevices)return;const ds=await navigator.mediaDevices.enumerateDevices();const cams=ds.filter(d=>d.kind==="videoinput");const sel=$("cameraSelect"),old=sel.value;sel.innerHTML='<option value="">Arka kamera (otomatik)</option>';cams.forEach((c,i)=>{const o=document.createElement("option");o.value=c.deviceId;o.textContent=c.label||`Kamera ${i+1}`;sel.appendChild(o)});if(cams.some(c=>c.deviceId===old))sel.value=old;}
  async function start(){await stop();setStatus("Kamera izni bekleniyor...");try{if(!window.ZXingBrowser)throw new Error("Barkod kütüphanesi yüklenemedi.");state.reader=new ZXingBrowser.BrowserMultiFormatReader();const device=$("cameraSelect").value||undefined;state.controls=await state.reader.decodeFromVideoDevice(device,$("cameraVideo"),(result)=>{if(result)submitBarcode(result.getText())});const video=$("cameraVideo");state.stream=video.srcObject;state.track=state.stream&&state.stream.getVideoTracks()[0];const caps=state.track&&state.track.getCapabilities?state.track.getCapabilities():{};$("torchButton").disabled=!caps.torch;await loadDevices();setStatus("Hazır. Barkodu çerçevenin ortasına gösterin.","success");ready();}catch(e){setStatus(e.message||"Kamera açılamadı.","error");$("lastResult").textContent="Kamera hatası";}}
  $("restartButton").onclick=start;$("cameraSelect").onchange=start;$("manualButton").onclick=()=>{submitBarcode($("manualBarcode").value);$("manualBarcode").value=""};$("manualBarcode").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();$("manualButton").click()}};$("torchButton").onclick=async()=>{if(!state.track)return;const on=$("torchButton").dataset.on!=="1";try{await state.track.applyConstraints({advanced:[{torch:on}]});$("torchButton").dataset.on=on?"1":"0";$("torchButton").textContent=on?"Feneri Kapat":"Fener"}catch(e){}};window.addEventListener("beforeunload",()=>{send({type:"CAMERA_CLOSED"});stop()});start();setInterval(ready,2500);
})();